log_level = "info"
http_server_host = "127.0.0.1"
http_server_port = 7000
secret_key = { seed={seed} }
port = 37000
tcp_port_reuse = bool
autonat_only_global_ips = false
autonat_throttle = 2
autonat_retry_interval = 10
autonat_refresh_interval = 30
autonat_boot_delay = 10
identify_protocol = "/avail_kad/id/1.0.0"
identify_agent = "avail-light-client/rust-client"
bootstraps = ["/ip4/13.51.79.255/udp/39000/quic-v1/12D3KooWE2xXc6C2JzeaCaEg7jvZLogWyjLsB5dA3iw5o3KcF9ds"]
relays = ["/ip4/13.49.44.246/udp/39111/quic-v1/12D3KooWBETtE42fN7DZ5QsGgi7qfrN3jeYdXmBPL4peVTDmgG9b"]
full_node_ws = ["ws://127.0.0.1:9944"]
app_id = 0
confidence = 92.0
avail_path = "avail_path"
ot_collector_endpoint = "http://otelcollector.avail.tools:4317"
log_format_json = true
block_matrix_partition = "1/20"
disable_proof_verification = false
disable_rpc = false
query_proof_rpc_parallel_tasks = 8
max_cells_per_rpc = 30
dht_parallelization_limit = 20
put_batch_size = 100
block_processing_delay = 0
sync_start_block = 0
sync_finality_enable = true
record_ttl = 86400
publication_interval = 43200
replication_interval = 10800
replication_factor = 20
connection_idle_timeout = 30
query_timeout = 60
query_parallelism = 3
caching_max_peers = 1
disjoint_query_paths = false
max_kad_record_number = 2400000,
max_kad_record_size = 8192,
max_kad_provided_keys = 1024
